### PR TITLE
making kubernetes installation as latest and generic instead of specific. 

### PR DESCRIPTION
**Pull request by sarathtadi**
Objective is to install the Objective is to install the latest kubernetes version(1.22.0) and made it generic instead of old version( 1.14.0 ) and added changes in files Kube-dependencies.yml and master-cluster.yml

Please approve.

### CODE REVIEW

**Comment by sarathtadi** [comment]
Please approve the pull request

**Comment by sarathtadi** [comment]
please approve the pull request

**Comment by sarathtadi** [comment]
please approve the pull request.

**Comment by sarathtadi** [comment]
please approve the pull request

**Comment by digitalvarys** [comment]
Looks good and closing

**Pull request merged**
